# Generated by Django 4.2.10 on 2025-01-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
    ]
